// Biblioteca de doenças e sinais — MATERIAL DE CONSULTA, NÃO É DIAGNÓSTICO.
// Fonte das fichas de TILÁPIA: Epagri (2019), Monocultivo de tilápia em viveiros escavados em SC, cap. 11 (pp. 92-107).
// Conteúdo resumido e reescrito; o que o livro não traz fica "DADO TÉCNICO A VALIDAR".
// Para exibir o crédito da foto, acrescente na ficha:  credito:'Autor, fonte, licença'
// Campos: nome, cat, foto (img/doencas/arquivo.jpg — veja img/doencas/LEIA-ME.txt), especies, sinais, fatores, favorecem, prevencao, manejo, profissional, fonte
const VALIDAR = ['DADO TÉCNICO A VALIDAR'];
const PROF = 'Procure médico veterinário ou técnico de aquicultura: em caso de mortalidade anormal, vários peixes com sinais ao mesmo tempo, ou dúvida sobre a causa. Antibióticos só com orientação profissional.';
const DOENCAS_CATEGORIAS = ['Bacterianas','Parasitárias','Fúngicas','Ambientais','Nutricionais','Qualidade da água'];
const DOENCAS = [
 { nome:'Columnariose (erosão das nadadeiras)', cat:'Bacterianas', foto:'img/doencas/columnariose.jpg', especies:['Tilápia'],
   sinais:['Manchas esbranquiçadas no corpo (perda da epiderme)','Podridão das nadadeiras','Mortalidade costuma ser rápida (até 48 h após as lesões)'],
   fatores:['Bactéria oportunista (Flavobacterium columnare), comum no ambiente','Lesões na pele por manejo excessivo ou estresse agudo (captura, classificação, transporte)','Má qualidade da água, muitos tricodinídeos, má nutrição'],
   favorecem:['Manejo em temperaturas altas','Fase de alevinagem e início do berçário'],
   prevencao:['Manejar em horários e temperaturas amenas (não manejar acima de 30 °C nem abaixo de 22 °C)','Manter a água adequada na alevinagem e berçário','Sal (4 g/L) em caixas de manejo, classificação, depuração e transporte','Aditivos na ração (vitamina C, probióticos, ácidos orgânicos) antes e depois do manejo'],
   manejo:['O livro trata de prevenção; para tratamento, procure assistência profissional'], profissional:PROF, fonte:'Epagri (2019), pp. 93-94' },
 { nome:'Septicemia hemorrágica bacteriana', cat:'Bacterianas', foto:'img/doencas/septicemia-hemorragica.jpg', especies:['Tilápia (mais comum em alevinos e juvenis)'],
   sinais:['Perda de apetite e natação errática','Úlceras ou pontos hemorrágicos no corpo','Hemorragia na borda das nadadeiras, abdômen distendido','Pontos hemorrágicos em órgãos internos (fígado, rim, coração, baço)'],
   fatores:['Enterobactérias oportunistas (Aeromonas móveis, Edwardsiella)'],
   favorecem:['Excesso de matéria orgânica no viveiro','Oxigênio dissolvido baixo','Má nutrição'],
   prevencao:['Nutrição adequada; aditivos alimentares podem ajudar','Boa qualidade de água e de solo','Boas práticas no transporte e na transferência de animais'],
   manejo:VALIDAR, profissional:PROF, fonte:'Epagri (2019), pp. 95-96' },
 { nome:'Estreptococose', cat:'Bacterianas', foto:'img/doencas/estreptococose.jpg', especies:['Tilápia (mortalidade costuma ocorrer acima de 500 g)'],
   sinais:['Desorientação e natação errática','Perda de apetite, hemorragia na base das nadadeiras','Abdômen distendido, inflamação da córnea, olho saltado (exoftalmia) em estágio avançado','Escurecimento do corpo; hemorragias ou abscessos no corpo, boca e ânus'],
   fatores:['Bactérias do gênero Streptococcus (S. agalactiae é a mais comum no Brasil)','Alevinos sem sinais podem ser fonte de contaminação; há transmissão dos pais para os filhos'],
   favorecem:['Água acima de 30 °C','Altas densidades (casos em viveiros com mais de 8 peixes/m², biomassa acima de 50 t/ha)'],
   prevencao:['Não povoar viveiro escavado com mais de 6 peixes/m²','Vazio sanitário de 1 mês entre ciclos','Cuidado no manuseio, principalmente com calor','Comprar alevinos de produtor de confiança','Vacina existe (única para tilápia); custo alto, indicada em cultivos superintensivos ou para reprodutores'],
   manejo:['O livro cita florfenicol como o antibiótico mais recomendado; dose e uso apenas com médico veterinário','Uso preventivo de antibiótico deve ser evitado (seleciona bactérias resistentes)'], profissional:PROF, fonte:'Epagri (2019), pp. 96-98' },
 { nome:'Franciselose', cat:'Bacterianas', foto:'img/doencas/franciselose.jpg', especies:['Tilápia (aguda em alevinos e juvenis; crônica em adultos)'],
   sinais:['Apatia, cor escura, natação errática, lesões nas nadadeiras, brânquias hemorrágicas, olhos opacos','Nódulos brancos nos órgãos internos, principalmente rins','Pontos negros no filé (podem condenar até 15 %)','Surtos agudos com mortalidade de até 60 %'],
   fatores:['Bactéria Francisella noatunensis subsp. orientalis','Espalha-se por transporte de peixes infectados; também passa dos pais para os filhos'],
   favorecem:['Inverno (abaixo de 24 °C) ou grandes variações de temperatura (outono)','Densidades acima do recomendado'],
   prevencao:['Evitar importar alevinos ou reprodutores de outros estados com surtos','Respeitar as densidades recomendadas'],
   manejo:['Doença de notificação obrigatória ao MAPA; em SC, notificar a Cidasc. A propriedade é interditada até o fim do tratamento e laudo de laboratório credenciado','Sem vacina; tratamento com antibiótico sob médico veterinário (o livro cita florfenicol)'],
   profissional:'Suspeita: avise imediatamente a Cidasc e procure médico veterinário. Não trate por conta própria.', fonte:'Epagri (2019), pp. 98-100' },
 { nome:'Saprolegniose', cat:'Fúngicas', foto:'img/doencas/saprolegniose.jpg', especies:['Tilápia (todas as fases; larvas e alevinos mais suscetíveis)'],
   sinais:['Perda de apetite e natação errática','Perda de cor da pele','Em fase avançada, tufos marrons no corpo'],
   fatores:['Fungos oportunistas (Saprolegnia, Achlya, Dictyuchus)','Lesões e perda de escamas são porta de entrada'],
   favorecem:['Queda brusca de temperatura (ex.: em 24 h) ou frio prolongado (ex.: 1 semana)','Má qualidade da água, excesso de matéria orgânica, estresse'],
   prevencao:['Não manejar, fazer biometria ou transferir abaixo de 22 °C nem antes de frente fria','Não povoar alevino I perto do inverno (passar o inverno com peixes de pelo menos 50 g)','Ração com no mínimo 600 mg de vitamina C por kg','Usar aerador no inverno','Alcalinidade acima de 40 mg CaCO₃/L no inverno','Sal (4 g/L) na água de transporte ou manejo'],
   manejo:['Segundo o livro (2019), não há produto permitido em aquicultura para tratar saprolegniose: o foco é prevenção'], profissional:PROF, fonte:'Epagri (2019), pp. 100-102' },
 { nome:'Tricodinídeos', cat:'Parasitárias', foto:'img/doencas/tricodinideos.jpg', especies:['Tilápia'],
   sinais:['Brânquias pálidas','Manchas esbranquiçadas de aspecto leitoso','Peixes nadando junto às margens, como se tentassem tirar parasitos do corpo'],
   fatores:['Protozoários ciliados oportunistas, comuns na tilapicultura','Infestação intensa abre porta para outras doenças (ex.: columnariose); maior risco na larvicultura'],
   favorecem:['Sem consenso sobre sazonalidade, segundo o livro'], prevencao:VALIDAR, manejo:VALIDAR, profissional:PROF, fonte:'Epagri (2019), p. 102' },
 { nome:'Larvas de moluscos bivalves (gloquídio)', cat:'Parasitárias', foto:'img/doencas/gloquidio.jpg', especies:['Tilápia (mais em animais jovens)'],
   sinais:['Pele áspera, com feridas','Mortalidade em casos intensos (relato de até 90 % em alevinos sem tratamento)'],
   fatores:['Larvas de moluscos de água doce parasitam nadadeiras, brânquias e pele por 10 a 30 dias em geral'],
   favorecem:['Viveiros com baixa renovação de água','Épocas chuvosas de primavera e temperaturas mais altas','Compra de matrizes e alevinos já parasitados; larvas entrando pelo canal de abastecimento'],
   prevencao:['Retirar manualmente os moluscos na secagem do viveiro (ficam no lodo)','Cal virgem (150 a 200 g/m²) para eliminar formas jovens aderidas, com acompanhamento técnico','Descartar a água de transporte; não colocar no viveiro','Telas de 100 micras (0,1 mm) no abastecimento'],
   manejo:VALIDAR, profissional:PROF, fonte:'Epagri (2019), pp. 102-104' },
 { nome:'Ictiofitiríase (doença dos pontos brancos)', cat:'Parasitárias', foto:'img/doencas/ictiofitiriase.jpg', especies:['Tilápia (também jundiá e truta)'],
   sinais:['Muitos pontos brancos no corpo (mais fáceis de ver em alevinos)','Em adultos, confirmação por exame das brânquias ao microscópio'],
   fatores:['Protozoário Ichthyophthirius multifiliis','Avança rápido; pode matar até 100 % em menos de uma semana'],
   favorecem:['Manejo grosseiro seguido de mudança brusca de temperatura (frentes frias)'],
   prevencao:['Evitar manejo grosseiro e variações bruscas de temperatura'],
   manejo:['Segundo o livro (2019), não há medicamento legalizado para uso em piscicultura contra esse parasito'], profissional:PROF, fonte:'Epagri (2019), pp. 104-105' },
 { nome:'Inchaço abdominal por excesso de alimentação', cat:'Nutricionais', foto:'img/doencas/inchaco-abdominal.jpg', especies:['Tilápia'],
   sinais:['Inchaço abdominal, seguido de inflamação do intestino por bactérias entéricas e, por fim, morte'],
   fatores:['Excesso de ração'], favorecem:['Alimentar em excesso com água acima de 30 °C'],
   prevencao:['Seguir a tabela de alimentação como referência e observar sobras','Não alimentar com água acima de 32 °C ou abaixo de 16 °C'], manejo:VALIDAR, profissional:PROF, fonte:'Epagri (2019), p. 79' },
 { nome:'Intoxicação por nitrito', cat:'Qualidade da água', foto:'img/doencas/intoxicacao-nitrito.jpg', especies:['Tilápia'],
   sinais:['Sangue marrom','Peixes boquejando na superfície mesmo com oxigênio adequado','Prejuízo no crescimento; mortalidade em níveis altos'],
   fatores:['Nitrito se liga à hemoglobina e impede o transporte de oxigênio'],
   favorecem:['Problemas nos últimos meses de cultivo em viveiros semi-intensivos com densidades mais altas'],
   prevencao:['Monitorar nitrito quinzenalmente (semanalmente se houver problema)'],
   manejo:['Nível amarelo: reduzir a alimentação em 30 %, conferir alcalinidade, aumentar aeração, biorremediador, sal','Nível vermelho: não alimentar até normalizar, aeração, renovar a água de fundo, sal','Sal comum: 10 mg de sal para cada 1 mg de NO₂/L. Kg de sal = 10 × NO₂ (mg/L) × volume (m³) ÷ 1000'], profissional:PROF, fonte:'Epagri (2019), pp. 60-62, 66-67' },
 { nome:'Amônia tóxica elevada', cat:'Qualidade da água', foto:'img/doencas/amonia-toxica.jpg', especies:['Tilápia'],
   sinais:['Peixe não aproveita bem a ração (conversão alta)','Acima de 1 mg/L de N-NH₃: letargia e morte'],
   fatores:['A toxicidade sobe com pH e temperatura (4 a 8 % por °C entre pH 6 e 9)'],
   favorecem:['Sobras de ração, fezes, matéria orgânica no solo'],
   prevencao:['Monitorar amônia quinzenalmente'],
   manejo:['Nível amarelo: reduzir alimentação em 30 %, conferir alcalinidade, aumentar aeração, biorremediador','Nível vermelho: não alimentar, aeração, renovar água de fundo, biorremediador'], profissional:PROF, fonte:'Epagri (2019), pp. 59-60, 67' },
 { nome:'Oxigênio dissolvido baixo', cat:'Qualidade da água', foto:'img/doencas/oxigenio-baixo.jpg', especies:['Tilápia'],
   sinais:['Menor ganho de peso e pior conversão mesmo antes de haver mortalidade'],
   fatores:['O oxigênio cai de madrugada; dias nublados ou chuvosos seguidos pioram'],
   favorecem:['Peixes menores e temperaturas maiores consomem mais oxigênio'],
   prevencao:['Medir diariamente ao amanhecer; manter acima de 3 mg/L (acima de 4 mg/L na alimentação)'],
   manejo:['Abaixo de 3 mg/L pela manhã: verificar dimensionamento e horários dos aeradores e reduzir a taxa de alimentação se preciso'], profissional:PROF, fonte:'Epagri (2019), pp. 57-58, 66' }
];
